# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phbaer/dev/asguard/drivers/controldev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phbaer/dev/asguard/drivers/controldev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phbaer/dev/asguard/drivers/controldev/CMakeFiles /home/phbaer/dev/asguard/drivers/controldev/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phbaer/dev/asguard/drivers/controldev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named controldev

# Build rule for target.
controldev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 controldev
.PHONY : controldev

# fast build rule for target.
controldev/fast:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/build
.PHONY : controldev/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

Joystick.o: Joystick.cpp.o
.PHONY : Joystick.o

# target to build an object file
Joystick.cpp.o:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/Joystick.cpp.o
.PHONY : Joystick.cpp.o

Joystick.i: Joystick.cpp.i
.PHONY : Joystick.i

# target to preprocess a source file
Joystick.cpp.i:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/Joystick.cpp.i
.PHONY : Joystick.cpp.i

Joystick.s: Joystick.cpp.s
.PHONY : Joystick.s

# target to generate assembly for a file
Joystick.cpp.s:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/Joystick.cpp.s
.PHONY : Joystick.cpp.s

SliderBox.o: SliderBox.cpp.o
.PHONY : SliderBox.o

# target to build an object file
SliderBox.cpp.o:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/SliderBox.cpp.o
.PHONY : SliderBox.cpp.o

SliderBox.i: SliderBox.cpp.i
.PHONY : SliderBox.i

# target to preprocess a source file
SliderBox.cpp.i:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/SliderBox.cpp.i
.PHONY : SliderBox.cpp.i

SliderBox.s: SliderBox.cpp.s
.PHONY : SliderBox.s

# target to generate assembly for a file
SliderBox.cpp.s:
	$(MAKE) -f CMakeFiles/controldev.dir/build.make CMakeFiles/controldev.dir/SliderBox.cpp.s
.PHONY : SliderBox.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... controldev"
	@echo "... doc"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Joystick.o"
	@echo "... Joystick.i"
	@echo "... Joystick.s"
	@echo "... SliderBox.o"
	@echo "... SliderBox.i"
	@echo "... SliderBox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

